### DISCUSSION TITLE
Metadata Prototyping

### DISCUSSION THREAD

**Discussion by darkterminal** [StreetCommunityProgrammer/metaphore#28] [Ideas]
Everything displayed as HTML. Before saving metaphor data, we can split metaphor in markdown file with standard DEVto frontmatter, and create JSON file that contains post metadata, Like:

Here standard Devto frontmatter:

```yml
---
title: Hello, World!
published: true
tags: discuss, help
date: 20190701T10:00Z
series: Hello series
canonical_url: https://example.com/blog/hello
cover_image: article_published_cover_image
---
```

Post Metadata:
```json
{
   "title": "Hello World!",
   "publihsed": true,
   "tags": "discuss, help",
   "date": "20190701T10:00Z",
   "series": "Hello series",
   "canonical_url": "https://example.com/blog/hello",
   "cover_image": "/path/to/image/that-generate-by-gh-action.png",
   "content": "/path/to/post-markdown-content.md",
   "author": "/path/to/author-metadata.json"
}
```

Our keys:
- content
- author

Our Collections:
```bash
|--posts
|--authors
|--images
```

![Sample Flow](https://cdn.discordapp.com/attachments/977184650797670432/1081127722081865728/image.png)
