### ISSUE TITLE
Punk Idea: Create a GitHub workflow to generate .md when we add a label to metaphore issue

### ISSUE THREAD

**Issue by mkubdev** [StreetCommunityProgrammer/metaphore#6]
### Is your mind blowing punk idea is something that ~~wrong~~ different then other.

@mkubdev

### Tell me what you want to suggest

The action should look like this:

```yml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - uses: actions/checkout@v2
      # Install dependencies
      - name: Install dependencies
        run: |
          npm install @octokit/rest
      # Set up the GitHub API client
      - name: Set up the GitHub API client
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          const Octokit = require('@octokit/rest')
          const octokit = new Octokit({ auth: process.env.GITHUB_TOKEN })
      # Fetch the content of the issue
      - name: Fetch the content of the issue
        run: |
          const issueNumber = github.context.issue.number
          const { data: issue } = await octokit.issues.get({ owner: github.context.repo.owner, repo: github.context.repo.repo, issue_number: issueNumber })
          const content = issue.body
      # Generate the Markdown file
      - name: Generate the Markdown file
        run: |
          const fs = require('fs')
          fs.writeFileSync(`issue-${issueNumber}.md`, content)
```

Missing stuff is trigger this action when we put a *specific* label to accepted issue.
